### ISSUE TITLE
Monitor and reader status changes without reason

### ISSUE THREAD

**Issue by cryo75** [springcard/springcard-dotnet-pcsc-sdk#2]
I have an application that connects to an Evolis Quantum2 printer with built-in SpringCard Crazywriter which also has a SIM inside it.

I have a reader monitor based on the examples here:

```
private void StartReaderMonitor()
{
    StopReaderMonitor();

    //Start monitoring any connnected readers
    readers = new SCardReaderList(SCARD.SCOPE_USER, SCARD.ALL_READERS);
    readers.StartMonitor(new SCardReaderList.StatusChangeCallback(ReaderListChanged));
}
```

Sometimes the reader state immediately changes to "Absent" or "In use (shared)" and I cannot communicate with the reader. Usually the state should be "Present, not powered".

Is there a reason why this happens and is there a solution for this problem?

**Comment by springcard** [comment]
Dear cryo75, this has nothing to do with this SDK, but with the behavior of the device and/or of the other active PC/SC applications. Please contact our support team directly (https://www.springcard.com/en/contact?request=support)
